export default myFonts = {
  "ClarityCity-Black": require("../assets/font/ClarityCity-Black.ttf"),
  "ClarityCity-BlackItalic": require("../assets/font/ClarityCity-BlackItalic.ttf"),
  "ClarityCity-Bold": require("../assets/font/ClarityCity-Bold.ttf"),
  "ClarityCity-BoldItalic": require("../assets/font/ClarityCity-BoldItalic.ttf"),
  "ClarityCity-ExtraBold": require("../assets/font/ClarityCity-ExtraBold.ttf"),
  "ClarityCity-ExtraBoldItalic": require("../assets/font/ClarityCity-ExtraBoldItalic.ttf"),
  "ClarityCity-ExtraLight": require("../assets/font/ClarityCity-ExtraLight.ttf"),
  "ClarityCity-ExtraLightItalic": require("../assets/font/ClarityCity-ExtraLightItalic.ttf"),
  "ClarityCity-Light": require("../assets/font/ClarityCity-Light.ttf"),
  "ClarityCity-LightItalic": require("../assets/font/ClarityCity-LightItalic.ttf"),
  "ClarityCity-Medium": require("../assets/font/ClarityCity-Medium.ttf"),
  "ClarityCity-MediumItalic": require("../assets/font/ClarityCity-MediumItalic.ttf"),
  "ClarityCity-Regular": require("../assets/font/ClarityCity-Regular.ttf"),
  "ClarityCity-RegularItalic": require("../assets/font/ClarityCity-RegularItalic.ttf"),
  "ClarityCity-SemiBold": require("../assets/font/ClarityCity-SemiBold.ttf"),
  "ClarityCity-SemiBoldItalic": require("../assets/font/ClarityCity-SemiBoldItalic.ttf"),
  "ClarityCity-Thin": require("../assets/font/ClarityCity-Thin.ttf"),
  "ClarityCity-ThinItalic": require("../assets/font/ClarityCity-ThinItalic.ttf"),
};
